[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions."procesar-ia"]
  timeout = 26

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false